spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DATABASE}
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
  application:
    name: song-service
opentelemetry:
  exporter:
    otlp:
      protocol: http/protobuf
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSSSSS} [%thread] %-5level %logger{36} [%X{traceId}] - %msg%n"
  level:
    root: INFO
    org.springframework.security: DEBUG

server:
  error:
    whitelabel:
      enabled: false
  port: ${SERVER_PORT}

cors:
  allowed-origin: ${CORS_ALLOWED_ORIGIN}

springdoc:
  api-docs:
    path: "/docs"
  swagger-ui:
    path: "/swagger.html"
