apiVersion: v1
kind: Service
metadata:
  name: song-service-service
spec:
  selector:
    app: song-service
  ports:
    - port: 8082
      targetPort: 8080
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: song-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: song-service-deployment
  minReplicas: 1
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-service-deployment
  labels:
    app: song-service
spec:
  selector:
    matchLabels:
      app: song-service
  template:
    metadata:
      labels:
        app: song-service
    spec:
      containers:
        - name: song-service
          image: judahlit/moodify_song_service:latest
          # image: k3d-moodify:5000/song_service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 128Mi
              cpu: "1"
            limits:
              memory: 2Gi
              cpu: "1"
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: song-service-secret
                  key: mongo-uri
            - name: MONGO_DATABASE
              valueFrom:
                secretKeyRef:
                  name: song-service-secret
                  key: mongo-database
            - name: RABBIT_HOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: host
            - name: RABBIT_PORT
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: port
            - name: RABBIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: username
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: password
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://grafana-k8s-monitoring-alloy-receiver.default.svc.cluster.local:4318"
