name: Build and Test

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle

      - name: Build and test application
        env:
          MONGO_URI: mongodb://guest:guest@song-db:27017
          MONGO_DATABASE: song-db
          RABBIT_HOST: rabbitmq
          RABBIT_PORT: 5672
          RABBIT_USERNAME: guest
          RABBIT_PASSWORD: guest
          SERVER_PORT: 8080
        run: gradle build --no-daemon --info

      - name: Upload Test Artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ${{ github.workspace }}/build/reports/tests/test/*
