name: Build and Test

on:
  push:
    branches: ["main, develop"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle

      - name: Build and test application
        env:
          MONGO_HOST: mongo-db
          MONGO_PORT: 27021
          MONGO_USERNAME: username
          MONGO_PASSWORD: password
          MONGO_DATABASE: database
          SERVER_PORT: 8080
        run: gradle build --no-daemon --info
